decl-version 2.0
input-language MongoDB

ppt SoftwareAnalysis.book:::POINT
  ppt-type point
 variable _id
  var-kind variable
  rep-type java.lang.String
  dec-type ObjectId
  comparability 1
 variable title
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable isbn
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable pageCount
  var-kind variable
  rep-type int
  dec-type int
  comparability 1
 variable publishedDate
  var-kind variable
  rep-type java.lang.String
  dec-type datetime
  comparability 1
 variable thumbnailUrl
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable shortDescription
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable longDescription
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable status
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable num_authors
  var-kind variable
  rep-type int
  dec-type int
  comparability 1
 variable authors[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[3]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[4]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[5]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[6]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[7]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable num_categories
  var-kind variable
  rep-type int
  dec-type int
  comparability 1
 variable categories[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable categories[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable categories[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable categories[3]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2

