decl-version 2.0
input-language MongoDB

ppt SoftwareAnalysis.book:::POINT
  ppt-type point
 variable _id
  var-kind variable
  rep-type java.lang.String
  dec-type ObjectId
  comparability 1
 variable title
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable isbn
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable pageCount
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable publishedDate
  var-kind variable
  rep-type java.lang.String
  dec-type datetime
  comparability 1
 variable thumbnailUrl
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable shortDescription
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable longDescription
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable status
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable num_authors
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable authors[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[3]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[4]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[5]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[6]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable authors[7]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable num_categories
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable categories[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable categories[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable categories[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable categories[3]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2

ppt SoftwareAnalysis.counties_small:::POINT
  ppt-type point
 variable _id
  var-kind variable
  rep-type java.lang.String
  dec-type ObjectId
  comparability 1
 variable num_altSpellings
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable altSpellings[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable altSpellings[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable altSpellings[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable altSpellings[3]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable altSpellings[4]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable altSpellings[5]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable altSpellings[6]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable altSpellings[7]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable altSpellings[8]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable area
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable num_borders
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable borders[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[3]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[4]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[5]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[6]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[7]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[8]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[9]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[10]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[11]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[12]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[13]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable borders[14]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable num_callingCode
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable callingCode[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable callingCode[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable callingCode[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable capital
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable cca2
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable cca3
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable ccn3
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable cioc
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable num_currency
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable currency[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable currency[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable currency[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable demonym
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable landlocked
  var-kind variable
  rep-type boolean
  dec-type bool
  comparability 1
 variable num_languages
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable languages<ita>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<lat>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<rus>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<uzb>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<eng>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ara>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<smo>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<fra>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<bwg>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kck>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<khi>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ndc>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nde>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nya>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<sna>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<sot>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<toi>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tsn>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tso>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ven>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<xho>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<zib>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<afr>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nbl>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nso>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ssw>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<zul>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<spa>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<bis>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<vie>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nau>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nld>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<slv>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ukr>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<swa>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<cmn>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tvl>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tur>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<por>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tet>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ton>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tuk>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tgk>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tkl>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tha>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<crs>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<swe>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<slk>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<srp>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<som>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nor>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<msa>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tam>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nno>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nob>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<smi>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kin>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ron>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<pol>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<div>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<grn>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kor>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nep>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<deu>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<her>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<hgm>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kwn>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<loz>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ndo>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<hmo>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tpi>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<pau>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<fil>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<aym>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<que>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<urd>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mri>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nzs>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<niu>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<pih>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ber>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mfe>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<cal>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<cha>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mon>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mlg>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mya>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mlt>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mkd>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mah>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<zho>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<lav>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ltz>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<lit>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<sin>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<gil>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<lao>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<hat>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<sqi>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<bar>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<srd>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ind>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kir>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<glv>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<khm>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kaz>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<jpn>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<hin>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ell>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nrf>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<jam>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<heb>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<isl>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<arc>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ckb>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<fas>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<gle>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<hrv>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<hun>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kal>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<dan>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<fao>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<nfr>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<mey>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kat>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<fin>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<fij>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<hif>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<amh>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<est>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<cat>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<eus>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<glg>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<oci>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<tir>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ces>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<kon>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<lin>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<rar>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<sag>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<pap>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<zdj>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<gsw>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<roh>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<lua>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<bel>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<dzo>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<hye>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<bjz>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<bos>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<bul>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<ben>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<run>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<aze>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<prs>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable languages<pus>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable num_latlng
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable latlng[0]
  var-kind variable
  rep-type double
  dec-type float
  comparability 2
 variable latlng[1]
  var-kind variable
  rep-type double
  dec-type float
  comparability 2
 variable num_name
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable name<common>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable num_name<native>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable name<official>
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable region
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable subregion
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 1
 variable num_tld
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable tld[0]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable tld[1]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable tld[2]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable tld[3]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable tld[4]
  var-kind variable
  rep-type java.lang.String
  dec-type str
  comparability 2
 variable num_translations
  var-kind variable
  rep-type double
  dec-type int
  comparability 1
 variable num_translations<deu>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<fin>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<fra>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<hrv>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<ita>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<jpn>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<nld>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<por>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<rus>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<spa>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2
 variable num_translations<cym>
  var-kind variable
  rep-type double
  dec-type int
  comparability 2

